# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.define "docker-server"

  config.vm.network "public_network", ip: "192.168.1.5"

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus=1
     vb.name = "docker-server"
   end
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get upgrade -y
   SHELL
end
