# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.define "jenkins"
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "public_network", ip: "192.168.1.1"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus=1
     vb.name = "jenkins"
   end
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get upgrade
     apt-get install software-properties-common
   SHELL
end
