---
- name: update cache # apt update
  apt:
    update_cache: yes

- name: install nginx # apt install nginx
  apt:
     name: nginx

- name: copia index.html
  copy:
    src: index.html
    dest: /var/www/html # pasta do ubuntu
