# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.define "ansible-server"

  config.vm.network "public_network", ip: "192.168.1.100"

  # Sincroniza o arquivo de hosts com o caminho do ansible na vm
  config.vm.synced_folder File.expand_path("./inventario"), "/etc/ansible/"
  # Sincroniza as playbooks
  config.vm.synced_folder "./playbooks/", "/etc/ansible/roles"

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus=1
     vb.name = "ansible-server"
   end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get install -y ansible
     apt-get install -y python3
     apt-get install -y python3-pip
     apt-get install sshpass -y
     apt-get upgrade -y
   SHELL
end
